quarkus.http.accept-backlog=1024
quarkus.native.resources.includes=file.txt,countries.csv
quarkus.log.category."io.vertx.core".level=INFO

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkusbd

# Pool de conexiones
quarkus.datasource.jdbc.max-size=100
quarkus.datasource.jdbc.initial-size=10
quarkus.datasource.jdbc.acquisition-timeout=30

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false