quarkus.http.accept-backlog=1024
quarkus.native.resources.includes=file.txt,countries.csv
quarkus.log.category."io.vertx.core".level=INFO

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.reactive.url=postgresql://localhost:5432/quarkusbd

# Hibernate Reactive config
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true