quarkus.http.accept-backlog=1024
quarkus.native.resources.includes=file.txt,countries.csv
quarkus.log.category."io.vertx.core".level=INFO

# Métricas y monitoreo
quarkus.micrometer.export-prometheus.enabled=true
quarkus.micrometer.binder.jvm.enabled=true
quarkus.micrometer.binder.system.enabled=true
quarkus.micrometer.binder.executor-service.enabled=true


# === ORM Bloqueante (Imperativo) ===
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkusbd

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# === ORM Reactivo ===
quarkus.datasource.reactive.db-kind=postgresql
quarkus.datasource.reactive.username=postgres
quarkus.datasource.reactive.password=postgres
quarkus.datasource.reactive.url=postgresql://localhost:5432/quarkusbd

quarkus.hibernate-reactive.database.generation=update
quarkus.hibernate-reactive.log.sql=true